spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/spider?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

management:
  endpoints:
    web:
      base-path: /actuator
  endpoint:
    shutdown:
      enabled: true
